# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user'),
        ('main', '0002_selectedproduct'),
    ]

    operations = [
    ]
