# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merge_20171129_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 29, 21, 54, 55, 916192, tzinfo=utc))),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='selectedproduct',
            old_name='product',
            new_name='product_key',
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ManyToManyField(to='main.SelectedProduct'),
        ),
    ]
