# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171129_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 22, 4, 41, 91140, tzinfo=utc)),
        ),
    ]
