# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171129_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 22, 22, 4, 845132, tzinfo=utc)),
        ),
    ]
