# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 22:26
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171129_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
                ('address', models.CharField(max_length=2000)),
                ('cart_items', models.ManyToManyField(to='main.SelectedProduct')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 22, 26, 50, 738500, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='order_history',
            field=models.ManyToManyField(to='main.Order'),
        ),
    ]
